name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Set changed flags
        id: flags
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Initialize flags
          runpod=false

          # Loop through all changed files
          IFS=' ' read -r -a files <<< "$CHANGED_FILES"
          for file in "${files[@]}"; do
            [[ "$file" == docker/runpod-desktop/Dockerfile ]] && runpod=true
          done

          echo "runpod_changed=$runpod" >> $GITHUB_OUTPUT

      - name: Build and push Runpod DESKTOP IMAGE
        if: steps.flags.outputs.runpod_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod-desktop
          file: ./docker/runpod-desktop/Dockerfile
          push: true
          tags: samtyurenkov/runpod-desktop:latest

